CREATE TABLE logo_carousel (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    image_url text NOT NULL,
    alt_text text,
    display_order integer DEFAULT 0 NOT NULL,
    direction text NOT NULL
);

-- Enable Row Level Security
ALTER TABLE logo_carousel ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow public read access to logo_carousel" ON logo_carousel FOR SELECT USING (true);
CREATE POLICY "Allow admin access to logo_carousel" ON logo_carousel FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- Insert some dummy data for testing
INSERT INTO logo_carousel (image_url, alt_text, display_order, direction) VALUES
('https://placehold.co/200x100/white/black?text=Logo1', 'Logo 1', 1, 'rtl'),
('https://placehold.co/200x100/white/black?text=Logo2', 'Logo 2', 2, 'rtl'),
('https://placehold.co/200x100/white/black?text=Logo3', 'Logo 3', 3, 'rtl'),
('https://placehold.co/200x100/white/black?text=Logo4', 'Logo 4', 4, 'rtl'),
('https://placehold.co/200x100/white/black?text=Logo5', 'Logo 5', 5, 'rtl'),
('https://placehold.co/200x100/white/black?text=Logo6', 'Logo 6', 1, 'ltr'),
('https://placehold.co/200x100/white/black?text=Logo7', 'Logo 7', 2, 'ltr'),
('https://placehold.co/200x100/white/black?text=Logo8', 'Logo 8', 3, 'ltr'),
('https://placehold.co/200x100/white/black?text=Logo9', 'Logo 9', 4, 'ltr'),
('https://placehold.co/200x100/white/black?text=Logo10', 'Logo 10', 5, 'ltr');