CREATE TABLE pain_points (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    title text NOT NULL,
    description text,
    icon text,
    order_index integer DEFAULT 0 NOT NULL
);

ALTER TABLE pain_points ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to pain_points" ON pain_points FOR SELECT USING (true);
CREATE POLICY "Allow admin access to pain_points" ON pain_points FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');