create table
  public.faqs (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    question text not null,
    answer text not null,
    order_index integer,
    constraint faqs_pkey primary key (id)
  );