create table
  public.contact_submissions (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    full_name text not null,
    email text not null,
    phone_number text not null,
    business_name text not null,
    admin_notes text null,
    constraint contact_submissions_pkey primary key (id)
  );