create table
  public.progress_stages (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    title text not null,
    description text not null,
    order_index integer,
    constraint progress_stages_pkey primary key (id)
  );