create table
  public.pain_points (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    icon text not null,
    title text not null,
    description text not null,
    order_index integer,
    constraint pain_points_pkey primary key (id)
  );